Repository Laravel-Backpack/activity-log, pull requests merged in 2023-08, with the labels that each got.

#10 Readme menu cmd
  readme.md
Labels: Priority: MUST, documentation, Size: XS

#15 show array attributes like extras
  resources/views/columns/activity_changes.blade.php
  src/Http/Controllers/ActivityLogCrudController.php
Labels: Priority: SHOULD, Size: XS

#21 Update readme.md
  readme.md
Labels: Priority: MUST, Size: XS

#8 Support Backpack v6 + Bug fixing
  composer.json
  readme.md
  resources/lang/en/activity_log.php
  resources/lang/pt/activity_log.php
  resources/views/buttons/view_entry_logs.blade.php
  resources/views/buttons/view_model_logs.blade.php
  resources/views/columns/activity_changes.blade.php
  src/ActivityLogServiceProvider.php
  src/Helpers/ActivityLogHelper.php
  src/Http/Controllers/ActivityLogCrudController.php
  src/Http/Controllers/Operations/EntryActivityOperation.php
  src/Http/Controllers/Operations/ModelActivityOperation.php
  src/Models/ActivityLog.php
  src/Observers/ActivityObserver.php
  src/Traits/LogsActivity.php
Labels: Priority: COULD, Priority: SHOULD
